stadium = input("경기장은 어디입니까? ")
win = input("이긴팀은 어디입니까? ")
lose = input("진팀은 어디입니까? ")
mvp = input("우수선수는 누구입니까? ")
score = input("스코어는 몇대몇입니까? ")

print()
print("[기사내용] ===============================")
print("오늘", stadium, "에서 야구 경기가 열렸습니다.")
print(win, "과", lose, "은 치열한 공방전을 펼쳤습니다.")
print(mvp, "이 맹활약을 하였습니다.")
print("결국", win, "이", lose, "를", score, "로 이겼습니다.")
print("==========================================")
